accessSettings:
  oauthSettings:
    programmaticClients:
      - 1056842563084-eg896hk26smj3o5pat3gtvjko7ivqu6f.apps.googleusercontent.com
      - 1056842563084-kcshpku3it1dhehp50opr9ele2gko0e7.apps.googleusercontent.com
